### PR TITLE
fix dplyr-related test failures

### PR DESCRIPTION
**Pull request by yl790**
Signed-off-by: yl790 <yitao@rstudio.com>

### CODE REVIEW

**Comment by yl790** [comment]
image

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2547-1/781612ca-292b-4252-acc8-73a2b51659b4.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2547-2/6789c169-7760-46bd-8ba1-1f3a53780e70.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2547-3/f7e179b7-04bc-433d-80de-087e6882308b.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2547-4/45e012f0-4384-441a-bd2b-0bab9892a422.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2547-5/86ff7eb2-2e40-4513-acdf-84f21cf9e152.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2547-6/7442d36f-ee8f-4cc5-ad48-3248ba216772.txt).

**Pull request merged**
