### PR TITLE
ensure ft_one_hot_encoder.ml_pipeline() work as expected

### PR DESCRIPTION
**Pull request by yitao-li**

### CODE REVIEW

**Comment by mysakbm** [comment]
This won't solve the problem.
As far as I gathered: 
ft_one_hot_encoder_estimator does not work in spark version 2.4 correctly because you are testing only for "spark_require_version(spark_connection(jobj), "3.0.0")". That does make the code from the book Mastering Spark with R broke. The code is 

`
pipeline <-
  ml_pipeline(sc) %>%
    ft_string_indexer(input_col = "sex", output_col = "sex_indexed") %>%
    ft_string_indexer(input_col = "drinks", output_col = "drinks_indexed") %>%
    ft_string_indexer(input_col = "drugs", output_col = "drugs_indexed") %>%
    ft_one_hot_encoder_estimator(
      input_cols = c("sex_indexed", "drinks_indexed", "drugs_indexed"),
      output_cols = c("sex_encoded", "drinks_encoded", "drugs_encoded")
    ) %>%
    ft_vector_assembler(
      input_cols = c("age", "sex_encoded", "drinks_encoded",
                     "drugs_encoded", "essay_length"),
      output_col = "features"
    ) %>%
    ft_standard_scaler(input_col = "features", output_col = "features_scaled",
                       with_mean = TRUE) %>%
    ml_logistic_regression(features_col = "features_scaled",
                           label_col = "not_working")

# Apply the pipeline to dataset
ml_fit(pipeline, okc_train)`

and the output is : "Error (scratch_2.R#40):  requires Spark 3.0.0 or higher.".

If you use older function "ft_one_hot_encoder", you cannot use it on multiple columns as documentation suggests. And you are not testing it correctly. In your testthat function, you have following code:
`
 iris_tbl %&gt;%        ft_string_indexer("Species", "indexed", string_order_type = "alphabetDesc") %&gt;%        ft_one_hot_encoder("indexed", "encoded")
`
 Line 33-36. So, you are not testing multiple columns.

**Comment by mysakbm** [comment]
> This won't solve the problem.
> As far as I gathered:
> **ft_one_hot_encoder_estimator** does not work in spark version 2.4 correctly because you are testing only for `spark_require_version(spark_connection(jobj), "3.0.0").` The second parameter si required and it is minimum version 'required_max', the 'required_max' parameter is optional and by default is NULL. Better should be `spark_require_version(spark_connection(jobj), "2.4.0", required_max = "3.0.0")`. Otherwise the code from the book Mastering Spark with R to fail. The code is
> 
> `pipeline <- ml_pipeline(sc) %>% ft_string_indexer(input_col = "sex", output_col = "sex_indexed") %>% ft_string_indexer(input_col = "drinks", output_col = "drinks_indexed") %>% ft_string_indexer(input_col = "drugs", output_col = "drugs_indexed") %>% ft_one_hot_encoder_estimator( input_cols = c("sex_indexed", "drinks_indexed", "drugs_indexed"), output_cols = c("sex_encoded", "drinks_encoded", "drugs_encoded") ) %>% ft_vector_assembler( input_cols = c("age", "sex_encoded", "drinks_encoded", "drugs_encoded", "essay_length"), output_col = "features" ) %>% ft_standard_scaler(input_col = "features", output_col = "features_scaled", with_mean = TRUE) %>% ml_logistic_regression(features_col = "features_scaled", label_col = "not_working") `
> 
> `ml_fit(pipeline, okc_train)`
> 
> and the output is : "Error (scratch_2.R#40): requires Spark 3.0.0 or higher.".
> 
> If you use older function "ft_one_hot_encoder", you cannot use it on multiple columns as documentation suggests. And you are not testing it correctly. In your testthat function, you have following code:
> `iris_tbl %&gt;% ft_string_indexer("Species", "indexed", string_order_type = "alphabetDesc") %&gt;% ft_one_hot_encoder("indexed", "encoded")`
> Line 33-36. So, you are not testing multiple columns.

Added suggested solution.

**Comment by yitao-li** [comment]
Multi-column input is only supported in Spark 3.0 or above. So, the changes in https://github.com/sparklyr/sparklyr/pull/3135 should cover that scenario.

**Comment by mysakbm** [comment]
> @mysakbm Yes, the `required_max = "3.0.0"` bug you mentioned was already fixed in #3072 and released as part of sparklyr 1.7.

I have sparklyr 1.7.0 installed and have this problem... maybe some later version?

**Comment by mysakbm** [comment]
> Multi-column input is only supported in Spark 3.0 or above. So, the changes in #3135 should cover that scenario.

Ah, ok. I was then fooled by the documentation... And by the book [Master the Spark in R](https://therinspark.com/pipelines.html#use-cases), as you can clearly see in the first example. The book uses sparkl 2.3. 

Is the multi-column input really supported in Spark 3.0?

**Comment by yitao-li** [comment]
@mysakbm Yes, apparently the multi-column support for one-hot-encoder was part of Spark 3.0. E.g., see https://github.com/sparklyr/sparklyr/blob/main/tests/testthat/test-ml-feature-one-hot-encoder.R#L34-L41

**Pull request merged**
