### PR TITLE
Fix date type portability issues

### PR DESCRIPTION
**Pull request by yl790**
This PR does the following:

- Ensure `Date` types in R are serialized into Spark and deserialized back to R in portable ways (e.g., should not be affected by JVM time zone and should not involve silly things like floating point rounding errors)
- Set timezone to something very far from UTC in CI workflow so that timezone portability issues can be surfaced quickly

### CODE REVIEW

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-1/8f5c093e-4db1-4a9e-9639-d209fd3c09fa.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-3/0e372598-a2ce-4380-95ff-d103e10a95d1.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-4/7daad27f-244c-47f5-b1dd-b01a2683c968.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-5/321dda46-959d-4dec-9939-7be381f25f15.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-6/ae14b1a6-6ce1-4193-9231-d67143e9a26f.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-2/71e5f8ab-7f68-4ee0-8028-30507e3fefde.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-7/d84909c4-9b5d-48cc-bb24-2671cbe5ec61.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-8/35831c15-ba9c-4833-8145-84ca49c9fa05.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-10/0a78e60b-73f2-45d1-8794-8632bc04f169.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-11/c8c317ef-4530-49f2-8ebc-8e301a52f279.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-12/ebbc1e98-04ad-402e-9051-a1b116b4132e.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-13/caebe1d3-a5d1-4117-9951-3b84039af66d.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2546-14/4b475e53-31fb-4232-9bbc-d685792562e0.txt).

**Comment by yl790** [comment]
At this point probably will be easier to replace this with a new PR

**Pull request closed without merging**
