### PR TITLE
support stratified sampling with dplyr::group_by followed by dplyr::sample_* for Spark dataframes

### PR DESCRIPTION
**Pull request by yitao-li**
This brings the range of sampling functionalities sparklyr supports closer to what dplyr supports with R dataframes.

### CODE REVIEW

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-1/5725d139-d881-4a17-b3a7-e18d57e0a79b.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-2/16c14079-4f22-45f7-920f-0c77935205b1.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-3/c5a9a7d3-a74b-42a8-ade8-ed9a5491cb77.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-4/a626a0fc-7509-4963-acd6-c3626e3088bb.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-5/c47757e9-5ada-489f-ac15-fdeb0a489a26.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-6/3c708c91-aef7-43e1-9bfb-2ec885147640.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-7/d3dcb60e-84b7-4975-821e-8b85f9c1d6f3.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-8/3e82fc41-ff32-45fa-95d6-1e2e6d788d4f.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-9/849b3764-6053-44fe-ad29-64a682757821.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-10/5125b60a-db6e-4590-86ec-d439bc81a2a9.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2819-11/33a3fb22-eef6-4d73-a23b-c10324b2b5e9.txt).

**Comment by yitao-li** [comment]
Update: actually the changes in this PR only cover stratified sampling for `dplyr::sample_n`.
The same for `dplyr::sample_frac` will require another slightly more complicated change.

**Pull request merged**
