### PR TITLE
Fixing Databricks CI

### PR DESCRIPTION
**Pull request by falaki**
Databricks tests are failing `test-spark-apply-bundle.R`.

### CODE REVIEW

**Comment by falaki** [comment]
@yl790 would you please take a look? This commit broke Databricks CI tests: https://github.com/sparklyr/sparklyr/commit/7c8e80116dbabc30ae205f4db543581650da8036

**Comment by Loquats** [comment]
Thanks for taking care of this!

**Comment by falaki** [comment]
@javierluraschi and @yl790 are you OK with this change?

**Comment by yl790** [comment]
@falaki Looks good to me!
I still don't think (at least in principle) this test should be tar-ing everything that is within `.libPaths()`, but after reducing the number of dependencies needed for the CI environment, this could still be OK (while being the simplest way of making sure Databricks CI and other CI workflows are all happy).

**Pull request merged**
