### PR TITLE
Upgrade databricks-connect pip package to 6.5.1 in CI

### PR DESCRIPTION
**Pull request by Loquats**
This is the newest version of databricks-connect pip package.

### CODE REVIEW

**Comment by Loquats** [comment]
Note that the update actually applies to all PR's, since it is a package installed on jenkins, so we may see Databricks CI test failures elsewhere.

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2555-1/cc716b55-dbf0-4e57-86c3-10d12cca1b17.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2555-2/7f4cabf5-e7ac-43bb-8c01-82cf93104baa.txt).

**Comment by Loquats** [comment]
We expect `continuous-integration/jenkins/pr-merge` to fail because the jenkins  job is configured to always use the Jenkinsfile from master, which will start a Databricks cluster with DBR 6.4. This will be incompatible with the new 6.5 client. 

I manually ran the tests using the new jenkinsfile, and there are no failures.

**Pull request merged**
