### PR TITLE
Update DB Connect to 6.4.1 in CI

### PR DESCRIPTION
**Pull request by Loquats**

### CODE REVIEW

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-1/c9faef5e-b4b6-4b82-a002-84fe39959151.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-1/c9faef5e-b4b6-4b82-a002-84fe39959151.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-2/e686203c-e900-45c8-aa02-093be3d2c7a0.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-2/e686203c-e900-45c8-aa02-093be3d2c7a0.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-3/2d0004a7-c4c8-46f7-bc1d-d08fc85179f7.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-3/2d0004a7-c4c8-46f7-bc1d-d08fc85179f7.txt).

**Comment by liangz1** [comment]
Shall we remove README.Rmd L409 `spark_home <- system("databricks-connect get-spark-home")`? This instruction would fail if the databricks-connect virtualenv is not activated for the system. I think it would be easier to recommend users to get it manually from the terminal.

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-4/ca48b5a0-a7d8-438d-9a76-f2428bee6d74.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-5/7804811d-2ac3-4650-b2a4-68c523ce420a.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-5/7804811d-2ac3-4650-b2a4-68c523ce420a.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2437-6/e1a3e493-2e45-4d92-bfd6-86e8b063e5c7.txt).

**Pull request merged**
