### PR TITLE
Support sparklyr connect for Azure Synapse Analytics

### PR DESCRIPTION
**Pull request by Bob-Chou**
# Description
This PR proposes to enable [Azure Synapse Analytics](https://azure.microsoft.com/en-us/products/synapse-analytics) users to use `spark_connect(..., method="synapse")` to connect to an existing Azure Synapse Spark session.

# Context
Azure Synapse Analytics users can currently connect to Spark using native `spark_connect(..., method = "shell")`. However, this launches a new Spark session even if one is already running. Therefore a new connection method is needed to connect to the existing Spark session. 

Note that on Azure Synapse, there is always a running Spark application when users run `sparklyr` code.

# Implementation Details
1. When an Azure Synapse user executes `spark_connect(..., method = "synapse")`, function `synapse_connection` will be triggered
2. `synapse_connection` first launches the `sparklyr.Shell` and the `sparklyr.Backend` on the existing spark cluster of Azure Synapse, then connects to the cluster by `gateway_connection`
4.  Once the gateway connection is established, `synapse_connection` will query the existing `SparkSession` via `sparklyr` java reflection.
5. All synapse connection functions are organized in a new file `R/synapse_connection.R`.

### CODE REVIEW

**Comment by Bob-Chou** [comment]
Hello @edgararuiz, I hope I've reached out to the right person 😄. Can you help review the code if you get a chance? Thank you in advance.

**Comment by edgararuiz** [comment]
@Bob-Chou - Thank you for your PR. Would it be possible to add a test or two to this change? Also, do not worry about the errors on the latest run, I can take care of it

**Comment by edgararuiz** [comment]
Actually, the remaining issue is actually due to the change on this PR. Can you run "Document" against your PR and re-commit please?

**Comment by Bob-Chou** [comment]
Hey @edgararuiz I've updated the PR with tests for Synapse connection. Can you help take a look when you get a chance? I appreciate your help.

image

**Comment by Bob-Chou** [comment]
Some tests are failing. I’m not sure if they are related to this PR 😕 @edgararuiz can you help take a look? Thank you so much.

**Comment by Bob-Chou** [comment]
Hey Edgar @edgararuiz. I was wondering if you had a chance to check it out. I really appreciate you taking the time for this :)  Let me know if there's anything I can do.

**Comment by edgararuiz** [comment]
Thank you!

**Comment by Bob-Chou** [comment]
Thank you @edgararuiz for merging the PR! May I ask if there's any plan for the next release (i.e. when the changes will be available to sparklyr users)?

**Pull request merged**
