### PR TITLE
Use arrow::write_to_raw and set local timezone as needed (fixes #2439)

### LINKED ISSUE #2439: Set timezone when sending POSIXt data to Spark
https://issues.apache.org/jira/browse/ARROW-8566 was reported on `arrow`. In brief, in the latest release of `arrow`, we [fixed a bug in datetime data handling](https://github.com/apache/arrow/commit/507762fa51d17e61f08d36d3626ab8b8df716198): previously, a "GMT" timezone was hardcoded everywhere, while now we send the actual timezone. It appears that when this timezone is not set, at least in the version of Spark that the user was on, Spark crashes. 

I'm not sure where exactly the bug lies--it's possible that the Arrow Java library Spark is using doesn't have the same expectations as the C++ library that R is using--though I'll dig a bit more. Regardless, we can be defensive and protect against this failure in `sparklyr`. Since R interprets POSIXt data without a timezone set as being in the system's current timezone, doing something like this on columns of data before sending to Spark should fix the issue:

```r
if (inherits(x, "POSIXt") && is.null(attr(x, "tzone"))) {
  attr(x, "tzone") <- Sys.timezone()
}
```

Would you be interested in a PR?

### PR DESCRIPTION
**Pull request by nealrichardson**
Also did some light refactoring in core_arrow.R.

I tried running configure.R per the comment, but it failed because I don't have scala installed. Are there developer docs somewhere? Happy to do the work, just don't want to make things worse by building with the wrong versions of scala java etc.

### CODE REVIEW

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2519-2/c403b6a9-1cc3-4f25-a849-865ffb85b718.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2519-1/f4addd5a-6d43-4bf7-9eac-952b0f690481.txt).

**Comment by yl790** [comment]
Hey @nealrichardson I updated the sparklyr development wiki page with the following:

https://github.com/sparklyr/sparklyr/wiki/Development#updating-embedded-sources

The good news is there is now a script that concatenates the core_* and worker_* R files and copies the result into all sparklyr_*.jar files directly without recompiling any of the scala sources. So, you actually won't need to run Rscript configure.R for this change.

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2519-3/527ef7cc-49d5-4a0e-ab3f-2e6261893971.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2519-4/311f0f5d-aba2-4c1e-a599-5932f617d98f.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2519-5/713f1cbd-30f7-484c-8c5d-cf134eea8314.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2519-6/3a3c2ab3-6d24-4f78-b128-5abfb69f022b.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2519-7/eca14e69-b02d-4f49-b690-a95a28fd97ab.txt).

**Pull request merged**
