### PR TITLE
support adls credential passthrough for databricks connections

### PR DESCRIPTION
**Pull request by yl790**
I think in theory this should fix the issue in https://github.com/sparklyr/sparklyr/issues/2342
I'm just not sure what's the easiest way to test such change E2E.

### CODE REVIEW

**Comment by stephlocke** [comment]
Unfortunately, this didn't fix the issue

**Comment by yl790** [comment]
@stephlocke  OK good to know... So the fs.azure.* config values are probably getting dropped yet again elsewhere.

I'm a bit busy with releasing sparklyr-1.2.0 at the moment. I'll try look more into this when I have time.

**Comment by stephlocke** [comment]
Much appreciated @yl790 !

**Comment by falaki** [comment]
Thanks for doing this. 

@stephlocke did you test this inside a Notebook or using Databricks Connect?

**Comment by falaki** [comment]
> Change looks reasonable, +1 for me since user confirmed the fix works properly. Would be nice to have a thumbs up from Databricks before merging (@falaki, @lu-wang-dl) but otherwise, I think we want this fix in the CRAN release.

Sorry I think I missed this and the release is over. I would follow up with this user because there are several discussions about ADLS passthrough especially with Databricks Connect.

**Comment by yl790** [comment]
Alright gonna merge this change then, because I think it's definitely a *prerequisite* for getting ADLS passthrough working.

**Pull request merged**
