### PR TITLE
Add {arrow} to Suggests

### PR DESCRIPTION
**Pull request by nealrichardson**
When the `arrow` interface was added to `sparklyr`, `arrow` was not yet on CRAN, so the package used some trickery to make it available. Now that `arrow` has been on CRAN for some time (coming up on 10 months), can we make it official?

I broke this PR into a few separate commits, in case you wanted to cherry-pick:

1. Add to `Suggests` and clean up core-arrow.R to use `arrow::` to access functions. I also worked out a solution to #2538 (unrelated) and included it in there in order to reduce churn on the .jar binaries.
2. Simplify the CI setup to use the normal `install.packages()` method for installing Arrow. One job installs from CRAN (or presumably RSPM, which will give you a neat binary), the other from our nightly package repo (bindings have to be compiled from source, but the Arrow C++ library should come as a binary). So this should speed up installation since you won't have to build Arrow C++ from source, and it means you don't have to maintain separate build scripts and cmake configuration for Arrow. This seems like a big win to me.
3. Remove a bunch of `if` statements to work around limitations of the pre-CRAN versions of Arrow and set a minimum version of 0.14, the first that reached CRAN. This makes core-arrow.R very short.
4. Remove some `skip_on_arrow()` for issues that have been fixed and note any open ARROW tickets that correspond to those skips. We can do this more easily now that we're not testing ancient Arrow versions on CI.

### CODE REVIEW

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2544-2/185a72e9-9aa6-4d99-b4e1-71f20d6fe5e4.txt).

**Comment by nealrichardson** [comment]
Arrow fails to install on the Databricks thing with `Try removing ‘/usr/lib/R/library/00LOCK-arrow’`.

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2544-1/64272a59-6e6e-4e67-8915-5be8ed12ffbc.txt).

**Comment by nealrichardson** [comment]
IIUC there's some spurious test failures due to the fact that dplyr 1.0 just got picked up

**Comment by yl790** [comment]
@nealrichardson Hey rebasing past https://github.com/sparklyr/sparklyr/commit/95259f90b3535e0400e3e8e705bede4dd0f8ecf9 should fix the wave of dplyr-related failures.

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2544-3/fedf7d5b-0ba5-4ef2-a48f-539726bf00a0.txt).

**Comment by yl790** [comment]
@nealrichardson Hey the change looks great overall, except for there is now some arrow-specific "sparklyr worker rscript failure" errors, possibly caused by something in `worker_apply.R` or `core_arrow.R`. I guess the easiest way to troubleshoot this is to run the same `spark-apply-ext` test cases with Arrow locally and see what's in the worker log file. Let me know if you need help.

**Comment by nealrichardson** [comment]
Thanks @yl790. I'm hoping to take a pass at those issues tomorrow. Re: CI reporting the worker logs, that would be great. My thought was to add something like

```yaml
      - name: Dump worker logs on failure
        if: failure()
        run: cat /tmp/worker.log
```

or you upload it as a build artifact. TBH I'll probably add that in this PR since I don't have great confidence in my ability to debug all of the issues locally--do you have a preference between `cat` vs. artifact?

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2544-4/528dd500-c064-4c4e-aeff-100433e25032.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2544-5/7c339e56-3c22-480d-8230-ef20fbaf6986.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2544-6/8f2be006-8eb3-4f72-8c41-9611d2cfa4fd.txt).

**Comment by nealrichardson** [comment]
Re `fetch_result_as_sdf`, I suspect it has never worked, or at least that particular test hasn't.  It was turned off for arrow < 0.17, and you weren't testing 0.17, only 0.16 and earlier. Arrow devel is > 0.17, but that CI job only runs selected test files, and that test wasn't one of them. So, nothing in my changes altered the behavior of that test/code, we are just running it on a different arrow version that wasn't excluded from that version check.

The error that occurred was in arrow, `NotImplemented: Converting vector to arrow type int8 not implemented` (forgive the ugly formatted traceback, it was a PITA to get at and understand the worker logs):

```
[13] "20/06/09 15:35:47 ERROR sparklyr: RScript (1324) collected callstack: "                                                                                                 
[14] "17: stop(structure(list(message = \"NotImplemented: Converting vector to arrow type int8 not implemented\", "                                                           
[15] "    call = Table__from_dots(dots, schema), cppstack = structure(list("                                                                                                  
[16] "        file = \"\", line = -1L, stack = c(\"1   arrow.so                            0x000000010ca698ea _ZN4Rcpp9exceptionC2EPKcb + 218\", "                            
[17] "        \"2   arrow.so                            0x000000010ca69795 _ZN4Rcpp4stopERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 53\", "         
[18] "        \"3   arrow.so                            0x000000010ca6c3af _ZN5arrow1r22VectorToArrayConverter5VisitEP7SEXPRECRKNSt3__110shared_ptrINS_8DataTypeEEE + 223\", "
[19] "16: Table__from_dots(dots, schema)"                                                                                                                                     
[20] "15: shared_ptr_is_null(xp)"                                                                                                                                             
[21] "14: shared_ptr(Table, Table__from_dots(dots, schema))"                                                                                                                  
[22] "13: Table$create(x)"                                                                                                                                                    
[23] "12: write_ipc_stream(x, sink) " 
```

Reading the test and code, I couldn't immediately see how/why there was an `int8` involved, but one way or another this should work, so we should follow up.

**Pull request merged**
