### PR TITLE
make dbExistsTable perform case-insensitive comparisons on table names

### PR DESCRIPTION
**Pull request by yitao-li**
Signed-off-by: Yitao Li <yitao@rstudio.com>

### CODE REVIEW

**Comment by nathaneastwood** [comment]
I think this fix might cause issues in instances where Spark is case-sensitive?

**Comment by yitao-li** [comment]
@nathaneastwood Are you referring to instances where `spark.sql.caseSensitive` is set to "true"? I thought that configuration only applies to column name resolutions.

**Comment by nathaneastwood** [comment]
Ah, it's possible. Sorry, I'm not a Spark expert :D

**Comment by nathaneastwood** [comment]
Awesome 👍🏼

**Pull request merged**
