### PR TITLE
support formula syntax in higher-order functions

### PR DESCRIPTION
**Pull request by yl790**
The `~ .x + .y` syntax instead of `.(x, y) -> (x + y)` is probably what most data science folks are accustomed to, and it's also more compact.

### CODE REVIEW

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2551-4/fc069952-756e-408e-b793-b323ec85cb60.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2551-1/7fa005c3-c00f-4ef8-88ee-4aee971e1db9.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2551-3/8442e96e-8784-4ac2-b440-5917f59bd42d.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2551-2/099fbf4c-3a3e-4929-9bf5-b0656fd8f937.txt).

**Comment by javierluraschi** [comment]
This is a good change!

Could we consider changing the signature of all the `hof_` functions to something like:

```r
hof_* <- function(x, f, input = tail(colnames(x), 1), output = input, ...) {
}
```

That way, we can write code like:

```r
sdf_len(sc, 100) %>% hof_filter(~ .x > 5)
```

I would also consider changing the title / description for these functions to something more user friendly and adding a simple example to each function, like:

**Title:** Filter Spark DataFrame with Expression
**Description:** Filters a Spark DataFrame using a high order function specified as an expression.
**Example:** `sdf_len(sc, 100) %>% hof_filter(~ .x > 5)`

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2551-5/8a38dd81-c833-4ad9-abbc-4c2519ece30d.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2551-6/52647345-c48c-45b2-a97c-fb8181029c21.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2551-7/8af65f8d-25d8-409c-9818-54e47060141a.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2551-8/80a9de9c-ee41-4cbc-ab6b-3a7ba201df9b.txt).

**Pull request merged**
