### PR TITLE
[WIP] optimize sdf collect

### PR DESCRIPTION
**Pull request by yl790**

### CODE REVIEW

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2430-1/e837c66a-6f30-4551-8a1b-9a3dd4cdd420.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2430-1/e837c66a-6f30-4551-8a1b-9a3dd4cdd420.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2430-2/34ae6b92-3af2-4cb1-97ea-9403f09df065.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2430-2/34ae6b92-3af2-4cb1-97ea-9403f09df065.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2430-3/0d37bc60-7a75-41b7-b42f-b232895bd6aa.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2430-4/23234dcf-0b54-45a6-bd44-fb2cbf8ed365.txt).

**Comment by yl790** [comment]
I think this code change is more or less what I want it to be by now :)
Just waiting for some benchmarks to happen (somewhat time consuming) and then this PR should be ready for review.

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2430-5/cf99145a-4970-4627-85c8-693ec204dc6f.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2430-6/1e7b00e9-2e03-42a2-9036-d4ddddf0f7a6.txt).

**Comment by yl790** [comment]
git is showing some incorrect diffs... now need to create another PR with the correct list of changes

**Pull request closed without merging**
