### PR TITLE
support deserializing struct types within arrays or nested arrays

### PR DESCRIPTION
**Pull request by yl790**
This PR addresses the deserialization issue described in https://github.com/sparklyr/sparklyr/issues/2419

### CODE REVIEW

**Comment by falaki** [comment]
@yl790 if you rebase this PR you will be able to see Jenkins log for Databricks tests since I merged https://github.com/sparklyr/sparklyr/pull/2421

I see two test failures:
```
test-sdf-collect.R:58: error: sdf_collect() works with structs inside arrays
```
and
```
test-sdf-collect.R:97: error: sdf_collect() works with structs inside nested arrays
```

**Comment by yl790** [comment]
rebasing & looking into Databricks CI failure as suggested

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2420-3/223e1d5c-d470-4bc5-9c16-bac31ff344e7.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2420-4/d504f23d-6539-4bf1-829c-610a05686f85.txt).

**Comment by yl790** [comment]
Tests now work with Databricks

**Comment by yl790** [comment]
@falaki hey re: Databricks Connect test -- I revised my test cases to only read sample data from text files such as `tests/testthat/data/struct-inside-arrays.json`, and saw when they were run in Databricks, there were some file copying happening as expected (e.g., "tests/testthat/data/struct-inside-arrays.json -> dbfs:/tmp/data/struct-inside-arrays.json"), but about maybe 1 out of 3 times, the test cases were still failing with dbfs:/tmp/data/struct-inside-arrays.json file not found exception later on in Databricks. Any idea why?

**Pull request merged**
