### PR TITLE
revise sparklyr.Utils.collect to read data row-by-row rather than column-by-column

### PR DESCRIPTION
**Pull request by yl790**
- Main benefit of this change is it gives user an option to avoid calling `df.collect` to fetch the entire data frame onto the driver node. This is done by setting `optimize_mem_util` to true when calling `sdf_collect` (makes sense to do so if the data frame is very large and working on one partition at a time reduces memory footprint at the cost of slightly higher performance overhead)
- Was hoping collecting data row-wise would produce some perf gain as well (because there will likely be more cache locality when working with an array of `Row`s) but so far a number of benchmarks on small and large data frames showed this change appear to be performance-neutral. A bit surprised by it TBH. Either there wasn't really a lot more cache hits, or the increased cache hits did not figure prominently in overall perf numbers due to other larger overheads.
- Still need to update jar files on the livy branch to fix livy test failures from this change -- ignore livy test failures for now
- Bonus point: this change allows us to avoid all the `local.map{row => { ... }` boilerplate code in many places. So, code-readability improved a bit as well : ) Yay.

Signed-off-by: yl790 <yitao@rstudio.com>

### CODE REVIEW

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-1/c3ac1c6b-5326-4643-8d81-ceb3e00dd138.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-1/c3ac1c6b-5326-4643-8d81-ceb3e00dd138.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-2/11dfcb68-41f8-4fc7-861a-0fb109f6a186.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-3/6b2e42eb-b1e7-414f-a78b-9cc7f9eb4b31.txt).

**Comment by javierluraschi** [comment]
@yitao-li Does this somehow overlaps with https://therinspark.com/data.html#copy? Specifically:

```r
dir.create("large")
spark_read_text(sc, "largefile.txt", memory = FALSE) %>%
  head(10^6) %>%
  collect(callback = function(df, idx) {
    writeLines(df$line, paste0("large/large-", idx, ".txt"))
  })
```

I don't think so, but want to double check.

The `callback` feature was my attempt to support retrieving large datasets to disk, is probably not used much but is definitely handy when needed. There might be better ways to implement this, so just wanted to throw this reference here.

**Comment by javierluraschi** [comment]
Regardless, I think letting users choose between column-wise and row-wise makes sense! I'd just suggest we rename `optimize_mem_util` to `row_wise`, or perhaps add a `strategy` parameter that could be set to `"columns"` or `"rows"`.

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-4/7c8d004f-d15c-4f37-8c12-ef27fbd77c42.txt).

**Comment by yl790** [comment]
@javierluraschi Great suggestion!
I don't think this change has much overlap with the callback feature -- although I definitely can see how both of them could be useful for reducing memory footprint in some cases.

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-5/a252858c-3fc5-4cbe-a84b-1aaed0b92053.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-6/efe18588-70a3-42d5-9b38-46118fa5f85d.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-7/2da7db67-2fa5-4262-9559-f527012b0378.txt).

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-8/3d6b6fe2-7991-4a7b-bc26-f253b9992e7f.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2434-9/6a9bfff7-1607-4a00-87a3-0e64d46639d2.txt).

**Comment by yl790** [comment]
- Revised as Javier suggested
- Will need to create a new Livy branch

**Pull request merged**
