### PR TITLE
enable some basic tests to run on Databricks connect

### PR DESCRIPTION
**Pull request by yl790**
just need to re-write those slightly so that they work in all CI envs -- there's no need to put `skip_databricks_connect()` everywhere

### CODE REVIEW

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2425-1/2d2c9247-a3b6-4fab-af1f-aec3f8d2d375.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2425-2/95bdd62e-b6dc-4df2-9de3-ee06ab7c4eeb.txt).

**Comment by yl790** [comment]
Hmm saw there were some file copies such as "tests/testthat/data/spark-read-csv-can-rename-columns.csv -> dbfs:/tmp/data/spark-read-csv-can-rename-columns.csv" happening as expected on Databricks before tests are run, but later on some test is failing with "org.apache.spark.sql.AnalysisException: Path does not exist: dbfs:/tmp/data/spark-read-csv-can-rename-columns.csv"

This is confusing. I probably won't work on this further until the dbfs file not found issue is resolved.

**Comment by falaki** [comment]
Thanks for doing this. I am looking into the intermittent error with files on DBFS. It might be because of S3 eventual consistency. I will also fix the status being green while tests failed.

**Comment by falaki** [comment]
@yl790 I addressed DBFS file issues https://github.com/sparklyr/sparklyr/pull/2427

Would you please rebase and run Databricks CI again? Also now if tests fail the status will be correctly updated.

**Comment by falaki** [comment]
Thanks and LGTM

**Pull request merged**
