### PR TITLE
[DO NOT MERGE] Build Spark 2.4 jars with Scala 2.12

### PR DESCRIPTION
**Pull request by falaki**
Adding scala 2.12 jar for spark 2.4 target

Addresses #2428

### CODE REVIEW

**Comment by falaki** [comment]
@javierluraschi can we cherry-pick this into the release branch?

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2429-1/a9c65c57-908d-45b6-8b27-10e0e6b148b6.txt).

**Comment by falaki** [comment]
Databricks Connect tests succeeded. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2429-2/169f0b75-709a-40e4-9f2d-722b9801191b.txt).

**Comment by javierluraschi** [comment]
@yl790 would have to port this to the [feature/sparklyr-1.2.0](https://github.com/sparklyr/sparklyr/tree/feature/sparklyr-1.2.0) branch.

**Comment by falaki** [comment]
@javierluraschi are you OK if I enable CI tests for the new JAR?

**Comment by falaki** [comment]
Databricks Connect tests failed. View logs [here](https://sparklyr-jenkins.s3.amazonaws.com/logs/jenkins-sparklyr-PR-2429-3/b2045f6f-fa1b-4110-b5d4-97f76b1fcde0.txt).

**Comment by yl790** [comment]
Hey there might be some interesting compiler change from Scala 2.11 to Scala 2.12 we need to watch out for, for example:

in Scala 2.11:

```
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_241).
Type in expressions for evaluation. Or try :help.

scala> var x: Integer = null
x: Integer = null

scala> x * x
java.lang.NullPointerException
  at scala.Predef$.Integer2int(Predef.scala:362)
  ... 32 elided

```

, and in Scala 2.12:

```
Welcome to Scala 2.12.10 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_241).
Type in expressions for evaluation. Or try :help.

scala> var x: Integer = null
x: Integer = null

scala> x * x
res0: Int = 0

```,

and possibly others like the ones above a well. Unsure how much such differences would actually affect Databricks or Sparklyr though.

Of course one could always argue `null` is a Java-ism that shouldn't have its place in Scala lexicon, but there could be places where Spark needs to interoperate with both Java and Scala and differences between Scala 2.11 and Scala 2.12 such as the above could matter.

**Pull request closed without merging**
